name: Deploy to Vercel with Redeploy-on-Failure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Link Vercel Project
        run: |
          npx vercel link --cwd . --yes \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" \
            --project "$VERCEL_PROJECT_ID"

      - name: Deploy & Redeploy on Failure
        shell: bash
        run: |
          set +e
          DEPLOY_LOG=$(npx vercel --prod --confirm \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" 2>&1)
          echo "$DEPLOY_LOG"
          DEPLOY_URL=$(echo "$DEPLOY_LOG" | grep -Eo 'https?://[A-Za-z0-9.-]+\.vercel\.app' | head -n1)
          if echo "$DEPLOY_LOG" | grep -q 'Error!'; then
            echo "❗️ 초기 배포 실패 — 재배포: $DEPLOY_URL"
            npx vercel redeploy "$DEPLOY_URL" \
              --token "$VERCEL_TOKEN" \
              --scope "$VERCEL_ORG_ID"
            if [ $? -ne 0 ]; then
              echo "::error::Redeploy도 실패했습니다!"
              exit 1
            fi
          fi
