name: Deploy to Vercel with Redeploy-on-Failure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x" }

      - name: Link Vercel Project
        run: |
          npx vercel link --yes \
            --scope "$VERCEL_ORG_ID" \
            --project "$VERCEL_PROJECT_ID"

      - name: Link Vercel Project
        run: |
          npx vercel link --cwd . --yes \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" \
            --project "$VERCEL_PROJECT_ID"

      - name: Deploy & Redeploy on Failure
        shell: bash
        run: |
          set +e

          # 1) 프로덕션 배포 실행 (로그 캡처)
          npx vercel --prod --confirm \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" > deploy.log 2>&1
          EXIT_CODE=$?
          cat deploy.log

          # 2) 실패(exit code != 0) 시 Redeploy 실행
          if [ $EXIT_CODE -ne 0 ]; then
            echo "❗ 초기 배포 실패 (exit code=$EXIT_CODE) — Redeploy 실행"

            # 배포 ID 파싱
            DEPLOY_ID=$(grep -Eo '/[A-Za-z0-9]{28}' deploy.log | head -n1 | tr -d '/')

            # Redeploy
            npx vercel redeploy "$DEPLOY_ID" \
              --token "$VERCEL_TOKEN" \
              --scope "$VERCEL_ORG_ID"

            # Redeploy 실패 시 에러 반환
            if [ $? -ne 0 ]; then
              echo "::error::Redeploy도 실패했습니다!"
              exit 1
            fi
          fi

          # 2) 배포 URL 추출
          URL=$(echo "$LOG" | grep -Eo 'https?://[A-Za-z0-9.-]+\.vercel\.app' | head -n1)

          # 3) 에러 감지 → redeploy
          if echo "$LOG" | grep -q 'Error!'; then
            echo "⚠️ 초기 배포 실패 — 같은 URL로 재배포: $URL"
            npx vercel redeploy "$URL" \
              --token "$VERCEL_TOKEN" \
              --scope "$VERCEL_ORG_ID"
            # redeploy도 실패하면 마지막에 exit 1 처리
            if [ $? -ne 0 ]; then
              echo "::error::Redeploy도 실패했습니다!"
              exit 1
            fi
          fi
