name: Deploy to Vercel with Redeploy-on-Failure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Deploy & Redeploy on Failure
        shell: bash
        run: |
          set +e
          # 1) 일반 배포 시도 (stdout+stderr 모두 캡쳐)
          DEPLOY_LOG=$(npx vercel --prod --confirm \
            --token "$VERCEL_TOKEN" \
            --org "$VERCEL_ORG_ID" \
            --project "$VERCEL_PROJECT_ID" 2>&1)
          echo "$DEPLOY_LOG"

          # 2) URL 파싱 (vercel CLI는 실패해도 URL을 먼저 출력합니다)
          DEPLOY_URL=$(echo "$DEPLOY_LOG" | grep -Eo 'https?://[a-zA-Z0-9.-]+\.vercel\.app' | head -n1)

          # 3) 에러 키워드 감지 → 같은 URL에 대해 Redeploy
          if echo "$DEPLOY_LOG" | grep -q 'Error!'; then
            echo "❗️ 초기 배포 실패, 동일 URL에 대해 재배포 실행: $DEPLOY_URL"
            npx vercel redeploy "$DEPLOY_URL" \
              --token "$VERCEL_TOKEN" \
              --confirm
            # 만약 두 번째도 실패 시 자동으로 에러 코드 반환
          fi
