name: Deploy to Vercel with Redeploy-on-Failure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x" }

      - name: Link Vercel Project
        run: |
          npx vercel link --yes \
            --scope "$VERCEL_ORG_ID" \
            --project "$VERCEL_PROJECT_ID"

      - name: Deploy & Redeploy on Failure
        shell: bash
        run: |
          set +e
          # 1) 프로덕션 배포 (debug 포함)
          LOG=$(npx vercel --prod --confirm --debug \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID" 2>&1)
          echo "$LOG"

          # 2) 배포 URL 추출
          URL=$(echo "$LOG" | grep -Eo 'https?://[A-Za-z0-9.-]+\.vercel\.app' | head -n1)

          # 3) 에러 감지 → redeploy
          if echo "$LOG" | grep -q 'Error!'; then
            echo "⚠️ 초기 배포 실패 — 같은 URL로 재배포: $URL"
            npx vercel redeploy "$URL" \
              --token "$VERCEL_TOKEN" \
              --scope "$VERCEL_ORG_ID"
            # redeploy도 실패하면 마지막에 exit 1 처리
            if [ $? -ne 0 ]; then
              echo "::error::Redeploy도 실패했습니다!"
              exit 1
            fi
          fi
